
// Incluye todos los departamentos y municipios que me pasaste.
window.municipiosData = {
  "Atlántida": [
    "La Ceiba",
    "Tela",
    "Jutiapa",
    "La Masica",
    "Esparta",
    "Arizona",
    "San Francisco",
    "Sonaguera",
    "Trujillo"
  ],
  "Choluteca": [
    "Choluteca",
    "Apacilagua",
    "Concepción de María",
    "Duyure",
    "El Corpus",
    "El Triunfo",
    "Marcovia",
    "Morolica",
    "Namasigüe",
    "Orocuina",
    "Pespire",
    "San Antonio de Flores",
    "San Isidro",
    "San José",
    "San Marcos de Colón",
    "Santa Ana de Yusguare"
  ],
  "Colón": [
    "Trujillo",
    "Balfate",
    "Iriona",
    "Limón",
    "Sabá",
    "Santa Fe",
    "Santa Rosa de Aguán",
    "Sonaguera",
    "Tocoa",
    "Bonito Oriental"
  ],
  "Comayagua": [
    "Comayagua",
    "Ajuterique",
    "El Rosario",
    "Esquías",
    "Humuya",
    "La Libertad",
    "Lamaní",
    "La Trinidad",
    "Lejamaní",
    "Meámbar",
    "Minas de Oro",
    "Ojos de Agua",
    "San Jerónimo",
    "San José de Comayagua",
    "San José del Potrero",
    "San Luis",
    "San Sebastián",
    "Siguatepeque",
    "Taulabé",
    "Villa de San Antonio",
    "Las Lajas"
  ],
  "Copán": [
    "Santa Rosa de Copán",
    "Cabañas",
    "Concepción",
    "Copán Ruinas",
    "Corquín",
    "Cucuyagua",
    "Dolores",
    "Dulce Nombre",
    "El Paraíso",
    "Florida",
    "La Jigua",
    "La Unión",
    "Nueva Arcadia",
    "San Agustín",
    "San Antonio",
    "San Jerónimo",
    "San José",
    "San Juan de Opoa",
    "San Nicolás",
    "San Pedro",
    "Santa Rita",
    "Trinidad de Copán",
    "Veracruz"
  ],
  "Cortés": [
    "San Pedro Sula",
    "Choloma",
    "Omoa",
    "Pimienta",
    "Potrerillos",
    "Puerto Cortés",
    "San Antonio de Cortés",
    "San Francisco de Yojoa",
    "San Manuel",
    "Santa Cruz de Yojoa",
    "Villanueva",
    "La Lima"
  ],
  "El Paraíso": [
    "Yuscarán",
    "Alauca",
    "Danlí",
    "El Paraíso",
    "Güinope",
    "Jacaleapa",
    "Liure",
    "Morocelí",
    "Oropolí",
    "Potrerillos",
    "San Antonio de Flores",
    "San Lucas",
    "San Matías",
    "Soledad",
    "Teupasenti",
    "Texiguat",
    "Vado Ancho",
    "Yauyupe",
    "Trojes"
  ],
  "Francisco Morazán": [
    "Distrito Central (Tegucigalpa)",
    "Alubarén",
    "Cedros",
    "Curarén",
    "El Porvenir",
    "Guaimaca",
    "La Libertad",
    "La Venta",
    "Lepaterique",
    "Maraita",
    "Marale",
    "Nueva Armenia",
    "Ojojona",
    "Orica",
    "Reitoca",
    "Sabanagrande",
    "San Antonio de Oriente",
    "San Buenaventura",
    "San Ignacio",
    "San Juan de Flores",
    "San Miguelito",
    "Santa Ana",
    "Santa Lucía",
    "Talanga",
    "Tatumbla",
    "Valle de Ángeles",
    "Villa de San Francisco",
    "Vallecillo"
  ],
  "Gracias a Dios": [
    "Puerto Lempira",
    "Ahuas",
    "Brus Laguna",
    "Juan Francisco Bulnes",
    "Ramal de Gracias a Dios",
    "Wampusirpi"
  ],
  "Intibucá": [
    "La Esperanza",
    "Camasca",
    "Colomoncagua",
    "Concepción",
    "Dolores",
    "Intibucá",
    "Jesús de Otoro",
    "Magdalena",
    "Masaguara",
    "San Antonio",
    "San Isidro",
    "San Juan",
    "San Marcos de la Sierra",
    "San Miguelito",
    "San Pedro de Tutule",
    "Santa Lucía",
    "Yamaranguila"
  ],
  "Islas de la Bahía": [
    "Roatán",
    "Utila",
    "Guanaja",
    "José Santos Guardiola"
  ],
  "La Paz": [
    "La Paz",
    "Cabañas",
    "Chinacla",
    "Guajiquiro",
    "Lamaní",
    "Lauterique",
    "Marcala",
    "Mercedes de Oriente",
    "Opatoro",
    "San Antonio del Norte",
    "San José",
    "San Juan",
    "San Pedro de Tutule",
    "Santa Ana",
    "Santa Elena",
    "Santa María",
    "Santiago de Puringla",
    "Yarula"
  ],
  "Lempira": [
    "Gracias",
    "Belén",
    "Camasca",
    "Cololaca",
    "Cucuyagua",
    "Erandique",
    "Gualcince",
    "Guarita",
    "La Campa",
    "La Iguala",
    "La Unión",
    "Las Flores",
    "La Virtud",
    "Lepaera",
    "Mapulaca",
    "Piraera",
    "San Andrés",
    "San Francisco",
    "San Juan Guarita",
    "San Manuel Colohete",
    "San Rafael",
    "San Sebastián",
    "Santa Cruz",
    "Tepetitán",
    "Tomalá",
    "Valladolid",
    "Virginia"
  ],
  "Ocotepeque": [
    "Ocotepeque",
    "Belén Gualcho",
    "Concepción",
    "Dolores Merendón",
    "Fraternidad",
    "La Encarnación",
    "La Labor",
    "Lucerna",
    "Mercedes",
    "San Fernando",
    "San Francisco del Valle",
    "San Jorge",
    "Sensenti",
    "Santa Fé"
  ],
  "Olancho": [
    "Campamento",
    "Catacamas",
    "Concordia",
    "Dulce Nombre de Culmí",
    "El Rosario",
    "Esquipulas del Norte",
    "Gualaco",
    "Guarizama",
    "Guata",
    "Guayape",
    "Jano",
    "Juticalpa",
    "La Unión",
    "Mangulile",
    "Manto",
    "Patuca",
    "Salamá",
    "San Esteban",
    "San Francisco de Becerra",
    "San Francisco de la Paz",
    "Santa María del Real",
    "Silca",
    "Yocón"
  ],
  "Santa Bárbara": [
    "Santa Bárbara",
    "Arada",
    "Atima",
    "Azacualpa",
    "Ceguaca",
    "Concepción del Norte",
    "Concepción del Sur",
    "El Nispero",
    "Gualala",
    "Ilama",
    "Las Vegas",
    "Macuelizo",
    "Naranjito",
    "Nueva Celilac",
    "Nueva Frontera",
    "Nuevo Celilac",
    "San Francisco de Ojuera",
    "San Jerónimo",
    "San José de Colinas",
    "San Luis",
    "San Marcos",
    "San Nicolás",
    "San Pedro Zacapa",
    "San Vicente Centenario",
    "Santa Rita",
    "Santa Rita de Jucuarán",
    "Trinidad",
    "Veracruz"
  ],
  "Valle": [
    "Nacaome",
    "Alianza",
    "Amapala",
    "Aramecina",
    "Caridad",
    "Goascorán",
    "Langue",
    "San Francisco de Coray",
    "San Lorenzo",
    "Valladolid"
  ],
  "Yoro": [
    "Yoro",
    "El Negrito",
    "El Progreso",
    "Jocón",
    "Morazán",
    "Olanchito",
    "Santa Rita",
    "Sulaco",
    "Victoria",
    "Yorito",
    "Aguanqueterique",
    "Mangulile",
    "San Antonio del Norte",
    "Santa Rita"
  ]
};